// components/Education.vue
<template>
  <div class="d-flex flex-column ga-4">
    <div
      class="text-h6 text-center text-md-start align-self-center align-self-md-start"
    >
      Education
    </div>

    <ul class="d-flex flex-column ga-4">
      <li>
        <div class="d-flex flex-column align-start">
          <a
            href="https://ice.uniwa.gr/en/home/"
            target="_blank"
            class="text-body-1 text-primary mb-1"
            >University of West Attica Department of Informatics and Computer
            Engineering</a
          >

          <div class="text-body-2 font-weight-bold">Athens, GR</div>
          <div class="text-body-2 mb-2 font-weight-bold">Semptember 2014</div>
        </div>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped></style>

// src/components/Education.tsx
import { Circle } from "@mui/icons-material";
import { Stack, Typography } from "@mui/material";

const Education = () => {
  return (
    <Stack gap={2}>
      <Typography
        variant="h6"
        sx={{ textAlign: { xs: "center", md: "start" } }}
      >
        Education
      </Typography>

      <Stack>
        <Stack direction="row" sx={{ alignItems: "center" }} gap={1}>
          <Circle sx={{ height: "8px", width: "8px" }} />

          <Typography
            variant="body1"
            component="a"
            href="http://www.ice.uniwa.gr"
            sx={{ color: "linkColor.main" }}
            target="_blank"
          >
            University of West Attica Department of Informatics and Computer
            Engineering
          </Typography>
        </Stack>

        <Stack sx={{ pl: "16px" }}>
          <Typography variant="body2" color="text.secondary">
            Athens, GR
          </Typography>

          <Typography variant="body2" color="text.secondary">
            September 2014
          </Typography>
        </Stack>
      </Stack>
    </Stack>
  );
};

export default Education;
