// components/GeneralInfo.vue
<template>
  <div
    class="bg-background3 rounded py-5 d-flex flex-column align-center align-md-stretch ga-5"
  >
    <div class="d-flex flex-column px-5">
      <div class="text-h5">Giannis Savvidis</div>
      <div class="text-body-2">Fullstack web developer</div>
    </div>

    <v-divider class="align-self-stretch" />

    <div class="d-flex flex-column ga-2 px-5">
      <div class="d-flex ga-2 align-center">
        <div class="text-body-2 font-weight-bold">Age:</div>

        <div class="text-body-2">{{ currentYear - 1996 }}</div>
      </div>

      <div class="d-flex ga-2 align-center">
        <div class="text-body-2 font-weight-bold">Location:</div>

        <div class="text-body-2">Athens, Greece</div>
      </div>

      <div class="d-flex ga-2 align-center">
        <div class="text-body-2 font-weight-bold">Email:</div>

        <a class="text-body-2 text-primary" href="mailto:gsavvidis96@gmail.com"
          >gsavvidis96@gmail.com</a
        >
      </div>

      <div class="d-flex flex-column pt-1 ga-2">
        <v-btn
          prepend-icon="mdi-github"
          color="secondary"
          density="comfortable"
          href="https://github.com/gsavvidis96"
          target="_blank"
          >GitHub</v-btn
        >

        <v-btn
          prepend-icon="mdi-linkedin"
          color="secondary"
          density="comfortable"
          href="https://www.linkedin.com/in/giannis-savvidis-22340a188/"
          target="_blank"
          >LinkedIn</v-btn
        >

        <v-btn
          prepend-icon="mdi-download-box"
          color="secondary"
          density="comfortable"
          href="CV.pdf"
          target="_blank"
          >Download CV</v-btn
        >
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const currentYear = new Date().getFullYear();
</script>

<style scoped></style>

// src/components/GeneralInfo.jsx
import { CloudDownload, GitHub, LinkedIn } from "@mui/icons-material";
import { Button, Divider, Paper, Stack, Typography } from "@mui/material";

const currentYear = new Date().getFullYear();

const GeneralInfo = () => {
  return (
    <Paper sx={{ backgroundColor: "cardBg.main" }} elevation={2}>
      <Stack sx={{ p: "20px" }}>
        <Typography variant="h5" sx={{ fontWeight: 500 }}>
          Giannis Savvidis
        </Typography>

        <Typography variant="body2" sx={{ textAlign: "center" }}>
          Fullstack web developer
        </Typography>
      </Stack>

      <Divider />

      <Stack sx={{ p: "20px" }} gap={1}>
        <Stack direction="row" sx={{ alignItems: "center" }} gap={1}>
          <Typography variant="body2" sx={{ fontWeight: 600 }}>
            Age:
          </Typography>

          <Typography variant="body2">{currentYear - 1996}</Typography>
        </Stack>

        <Stack direction="row" sx={{ alignItems: "center" }} gap={1}>
          <Typography variant="body2" sx={{ fontWeight: 600 }}>
            Location:
          </Typography>

          <Typography variant="body2">Athens, Greece</Typography>
        </Stack>

        <Stack direction="row" sx={{ alignItems: "center" }} gap={1}>
          <Typography variant="body2" sx={{ fontWeight: 600 }}>
            Email:
          </Typography>

          <Typography
            variant="body2"
            component="a"
            href="mailto:gsavvidis96@gmail.com"
            sx={{ color: "linkColor.main" }}
          >
            gsavvidis96@gmail.com
          </Typography>
        </Stack>

        <Stack sx={{ pt: 2 }} gap={1}>
          <Button
            variant="contained"
            color="primary"
            size="small"
            startIcon={<GitHub />}
            sx={{ textTransform: "none" }}
            component="a"
            href="https://github.com/gsavvidis96"
            target="_blank"
          >
            GitHub
          </Button>

          <Button
            variant="contained"
            color="primary"
            size="small"
            startIcon={<LinkedIn />}
            sx={{ textTransform: "none" }}
            component="a"
            href="https://www.linkedin.com/in/giannis-savvidis-22340a188/"
            target="_blank"
          >
            LinkedIn
          </Button>

          <Button
            variant="contained"
            color="primary"
            size="small"
            startIcon={<CloudDownload />}
            sx={{ textTransform: "none" }}
            href="giannis_savvidis_cv.pdf"
            download
          >
            Download CV
          </Button>
        </Stack>
      </Stack>
    </Paper>
  );
};

export default GeneralInfo;
